pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages{
    stage('checkout'){
      steps{
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/cloudjerry-14/Jenkins-CICD.git'
      }
    }
    stage('build'){
      agent{
        docker { image 'maven:latest'}
      }
      steps{
        sh 'cd springboot-k8s-argo-helm-CICD/jenkins-k8s-argo && mvn clean package'
      }
    }
  }
}
