pipeline {
  agent {
    docker {image 'ubuntu:latest'}	
  }
  stages{
    stage('Checkout'){
      steps{
        sh 'echo "Build"'
        git branch: 'main', url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git'
      }
    }
  }
}