pipeline {
  agent {
    docker {image 'ubuntu:latest'}	
  }
  stages{
    stage('Checkout'){
      steps{
        sh 'echo "Checkout code"'
        git branch: 'main', url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git'
      }
    }
    stage('Build'){
      agent {
        docker {image 'maven:latest'}	
  	  }
      steps{
        sh 'echo "Maven Build"'
        cd springboot-k8s-argo-helm-CICD/spring-boot-app
        mvn clean compile
      }
    }
  }
}