pipeline {
  agent {
    docker {image 'ubuntu:latest'}	
  }
  stages{
    stage('Checkout'){
      steps{
        sh 'echo "Checkout code"'
        git branch: 'main', url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git'
      }
    }
    stage('ChangeDir'){
      agent{
        docker {image 'ubuntu:latest'}
      }
      steps{
        sh 'echo CD'
        sh 'cd springboot-k8s-argo-helm-CICD/spring-boot-app'
      }
    }
    stage('Build'){
      agent {
        docker {image 'maven:3.8.4-openjdk-17'}	
  	  }
      steps{
        sh 'mvn clean compile'
      }
    }
  }
}