pipeline {
  agent none
    stages {
      stage('Build') {
        agent {
          docker { image 'maven:latest' }
        }
        steps{
            sh 'mvn --version'
            sh 'echo "maven"'          
        }
      }
      stage('frontend'){
        agent {
          docker{
            image 'node:latest'
          }
        }
        steps{
          sh 'node --version'
          sh 'echo "node"'
        }
      }
    }
  
}
